name: CI

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: build
      run: |
        cd build
        cmake --build .
